/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 correoD.glb --transform 
Files: correoD.glb [3.71KB] > C:\Users\PC\Documents\blenderModels\ICONOS\icono superprime\correoD-transformed.glb [3.15KB] (15%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/correoD-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Correo_1.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          geometry={nodes.Correo_2.geometry}
          material={materials.lambert2SG}
        />
      </group>
    </group>
  );
}
