/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 githubD.glb --transform 
Files: githubD.glb [6.46KB] > C:\Users\PC\Documents\blenderModels\ICONOS\icono superprime\githubD-transformed.glb [5.22KB] (19%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/githubD-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Github_1.geometry}
          material={materials["lambert2SG.001"]}
        />
        <mesh
          geometry={nodes.Github_2.geometry}
          material={materials["lambert3SG.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/githubD-transformed.glb");
