/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 linkedinD.glb --transform 
Files: linkedinD.glb [5.51KB] > C:\Users\PC\Documents\blenderModels\ICONOS\icono superprime\linkedinD-transformed.glb [4.98KB] (10%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/linkedinD-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.LinkedIn_1.geometry}
          material={materials["lambert3SG.002"]}
        />
        <mesh
          geometry={nodes.LinkedIn_2.geometry}
          material={materials["lambert2SG.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/linkedinD-transformed.glb");
