/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 personaD.glb --transform 
Files: personaD.glb [8.19KB] > C:\Users\PC\Documents\blenderModels\ICONOS\icono superprime\personaD-transformed.glb [8.06KB] (2%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/personaD-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Persona_1.geometry}
          material={materials["lambert2SG.003"]}
        />
        <mesh
          geometry={nodes.Persona_2.geometry}
          material={materials["lambert3SG.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/personaD-transformed.glb");
